# 🏆 NumPy Hands-On Session

**Topics Covered:**
- Basics of NumPy Arrays
- Array Operations
- Indexing & Slicing
- Mathematical & Statistical Functions
- Broadcasting
- Performance Optimization

**📌 Let's get started!**

In [1]:
import numpy as np  # Importing NumPy

## 1️⃣ Creating NumPy Arrays

In [2]:
# Creating an array from a list
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [3]:
# Array properties
print(f'Shape: {arr.shape}, Data Type: {arr.dtype}')

Shape: (5,), Data Type: int64


**📝 Exercise:** Create a 3x3 matrix filled with random numbers.

In [4]:
# Solution
matrix = np.random.rand(3, 3)
print(matrix)

[[0.70931708 0.9222779  0.77322761]
 [0.31606427 0.56177309 0.3262277 ]
 [0.62861701 0.18755231 0.90903535]]


## 2️⃣ Indexing & Slicing

In [5]:
# Accessing elements
print(arr[0], arr[-1])  # First and last element

1 5


**📝 Exercise:** Extract a subarray from the matrix.

In [6]:
# Solution
subarray = matrix[:2, :2]  # Top-left 2x2 submatrix
print(subarray)

[[0.70931708 0.9222779 ]
 [0.31606427 0.56177309]]


## 3️⃣ Mathematical Operations

In [7]:
# Element-wise operations
arr2 = np.array([10, 20, 30, 40, 50])
print(arr + arr2, arr * 2)

[11 22 33 44 55] [ 2  4  6  8 10]


**📝 Exercise:** Compute the mean and standard deviation of a large array.

In [8]:
# Solution
large_arr = np.random.randn(1000)
print(f'Mean: {np.mean(large_arr)}, Std Dev: {np.std(large_arr)}')

Mean: -0.012915088039816058, Std Dev: 1.0031356996089862


## 4️⃣ Broadcasting

In [9]:
# Broadcasting Example
arr3 = np.array([1, 2, 3])
print(arr3 + 10)  # Adds 10 to each element

[11 12 13]


## 5️⃣ Performance Optimization

In [10]:
# Vectorized Operation vs Loop
import time
A = np.random.rand(1000000)
B = np.random.rand(1000000)

# Using Loop
start = time.time()
C = [A[i] + B[i] for i in range(len(A))]
print(f'Loop Time: {time.time() - start:.5f} sec')

# Using NumPy
start = time.time()
C = A + B
print(f'NumPy Time: {time.time() - start:.5f} sec')

Loop Time: 0.47799 sec
NumPy Time: 0.03199 sec


## 🎯 Summary & Takeaways
- NumPy provides powerful array manipulation features.
- Operations are **vectorized**, making them fast.
- **Broadcasting** simplifies operations on different-sized arrays.
- Always prefer **NumPy over Python loops** for efficiency!

**🚀 Keep practicing and exploring!**